// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCopyrightAttribute("Copyright ©2017-2021 ICT Baden GmbH")]
[assembly: AssemblyCompanyAttribute("ICT Baden GmbH")]
[assembly: AssemblyProductAttribute("RevolutionPi .NET Library")]
[assembly: AssemblyVersionAttribute("0.5.4")]
[assembly: AssemblyFileVersionAttribute("0.5.4")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyCopyright = "Copyright ©2017-2021 ICT Baden GmbH";
        internal const System.String AssemblyCompany = "ICT Baden GmbH";
        internal const System.String AssemblyProduct = "RevolutionPi .NET Library";
        internal const System.String AssemblyVersion = "0.5.4";
        internal const System.String AssemblyFileVersion = "0.5.4";
    }
}
